name: flutter_playground
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  rflutter_alert: ^2.0.4
  audioplayers: ^0.20.1
  font_awesome_flutter: ^9.2.0
  geolocator: ^8.0.1
  http: ^0.13.4
  flutter_spinkit: "^5.1.0"
  animated_text_kit: ^4.2.1
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  modal_progress_hud: ^0.1.3
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/
  - images/dice/
  - images/story/
  - images/mi_card/
  - images/magic_8_ball/
  - images/clima/
  - images/flash_chat/
  - assets/xylophone/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900