name: flutter_playground
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  rflutter_alert: ^1.1.0
  audioplayers: ^0.16.2
  font_awesome_flutter: ^8.10.0
  geolocator: ^6.1.1
  http: ^0.12.2
  flutter_spinkit: "^4.1.2+1"
  animated_text_kit: ^3.1.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/
  - images/dice/
  - images/story/
  - images/mi_card/
  - images/magic_8_ball/
  - images/clima/
  - images/flash_chat/
  - assets/xylophone/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900